document.writeln("<section class=\"header-ask\">");
document.writeln("  <div class=\"back\"><a href=\"javascript:void(0)\" title=\"返回\">返回</a></div>");
document.writeln("  <h1>问题详情</h1>");
document.writeln("  <div class=\"search\"><a href=\"javascript:void(0)\" title=\"搜索\"></a></div>");
document.writeln("  <div id=\"header_tool_key\" class=\"header-tool-key\"></div>");
document.writeln("</section>");
document.writeln("<section class=\"sub\">");
document.writeln("  <p class=\"ellipsis-this xLocation\"> <a href=\"javascript:void(0)\" title=\"\">首页</a>&gt; <a target=\"_self\" href=\"javascript:void(0)\">健康频道</a> &gt; <a href=\"javascript:void(0)\" title=\"\">变大</a> </p>");
document.writeln("</section>");
document.writeln("<section class=\"tiezi-title\">");
document.writeln("  <div class=\"zt zt2\"><i>已解答</i></div>");
document.writeln("  <h1 class=\"ellipsis-this\"><span style=\"font-size: 15px;\">身上长红色小疙瘩，严重影响个人形象和生活，有什么健康有效的祛除鸡皮肤方法吗？</span></h1>");
document.writeln("  <div class=\"about\"> <cite class=\"msg\">家庭主妇&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;女&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;26岁 </cite> <cite class=\"time\">2016-02-14 21:36</cite> </div>");
document.writeln("</section>");
document.writeln("<section class=\"tiezi-qs\">");
document.writeln("  <p class=\"tiezi-ps\"><i>开始时间：</i>六年</p>");
document.writeln("  <p class=\"tiezi-ps\"><i>问题描述：</i>产后胸部缩水，眼睁睁看着胸从C变成了A，朋友们都开玩笑说：“你的胸是变成奶流完了吗？”期间也吃了很多网上说的使胸部变大方法，但是效果不大，体重却是越吃增加越厉害，吓的我赶紧停了下来。胸部缩水，让我非常痛苦，毕竟自己还年轻，不想让自己的形象就这么毁了，加上老公也开玩笑说我是“平板电脑”，这些玩笑让夫妻关系蒙上一层阴影，不想等问题出现了在去补救，求推荐一些健康有效的使胸部变大方法。</p>");
document.writeln("</section>");
document.writeln("<section class=\"spacing tiezi-bs\">");
document.writeln("  <div class=\"tiezi-bs-titles\">");
document.writeln("    <h2 class=\"t2\">相关问题</h2>");
document.writeln("  </div>");
document.writeln("  <ul class=\"ellipsis-ul list\">");
document.writeln("    <li><h4>产后胸部变小是什么原因？</h4><p style=\"display: block;\">常见的原因有产后，由于哺乳，怀孕都可以导致气血不足，脂肪减少，就会使乳房变小等。</p></li>");
document.writeln("    <li><h4>本人24岁乳房下垂乳头很小</h4><p style=\"display: none;\"> 可以补充孕激素、促进催乳素生成！没有结婚只有物理帮助了。</p></li>");
document.writeln("    <li><h4>要怎样调节内分泌失调?</h4><p style=\"display: none;\"> 要有好的饮食习惯，每天三餐按时吃饭，吃的东西要有营养，内分泌失调者如果营养跟不上的话会加重的，还有平时要养成好的睡眠习惯，每天按时睡觉。</p></li>");
document.writeln("    <li><h4>请问,青木瓜如果没有使胸部变大作用,会不会对乳房有不好的地方吗</h4><p style=\"display: none;\">你好,青木瓜没有使胸部变大作用,不会对乳房不好。</p></li>");
document.writeln("  </ul>");
document.writeln("</section>");
document.writeln("<section class=\"spacing tiezi-as\">");
document.writeln("<!-------------------------------------------------->");
document.writeln("<!--<div class=\"g-asklist t18 zhenshiAD\">        <div id=\"zhuanjiahuifuxia\"></div>");
document.writeln("		<div id=\"ad_bjp_box_114\"></div>");
document.writeln("	<div id=\"ad_bjp_box_115\"></div>");
document.writeln("	<div id=\"ad_bjp_box_116\"></div>");
document.writeln("	<div style=\"color:#333\" id=\"ad_bjp_box_117\"></div>");
document.writeln("	");
document.writeln("	<div style=\"margin:10px 15px 15px;\" class=\"g-expand\"><span style=\"background-color: #a6d57c; color: #fff; display: inline-block; line-height: 16px; padding: 0 5px;\">推广</span><a class=\"s_add_time\" rel=\"nofollow\" val=\"g3h46cxi2h3kf467|03j7gl8fojm047ga\" href=\"#\">达人分享变大达人经验！轻松变E！</a></div>	");
document.writeln("	<div style=\"margin:10px 15px 15px;\" class=\"g-expand\"><span style=\"background-color: #a6d57c; color: #fff; display: inline-block; line-height: 16px; padding: 0 5px;\">资讯</span><a class=\"s_add_time\" rel=\"nofollow\" val=\"ghjtgl8fojm047g7|0w6h0ca2nlwg3h0a\" href=\"#\">达人分享变大达人经验！轻松变E！</a></div>	");
document.writeln("    <div class=\"g-expand\" id=\"wyy_tuiguang_ad\"></div>");
document.writeln("</div>-->");
document.writeln("<!-------------------------------------------------->");
document.writeln("  <div class=\"titles\">");
document.writeln("    <h2>老师回答</h2>");
document.writeln("  </div>");
document.writeln("  <div class=\"ys\">");
document.writeln("    <div class=\"ys-msg\"> <img src=\"../../www.doujingqing.com/fengweixin/tx/1.jpg\"/*tpa=http://www.doujingqing.com/fengweixin/tx/1.jpg*/ alt=\"\"> <span>苏小青&nbsp;&nbsp;<cite class=\"ellipsis-this\">胸部老师&nbsp;&nbsp;&nbsp;&nbsp;全科</cite></span></div>");
document.writeln("    <p class=\"tiezi-ps\">常见的使胸部变大方法有食物使胸部变大，即通过调整饮食规律，借用蔬菜里面的营养物质达到使胸部变大目的，但这类见效缓慢一般可作为辅助措施；另一种使胸部变大，对胸部填充硅胶等制品达到使胸部变大目的，但这种使胸部变大一是风险大，二是影响乳房神经细胞对哺乳不利；草本使胸部变大，由于成分天然、搭配合理、营养足够，是目前女性使胸部变大常见的一种方法。女性使胸部变大是一种爱美的表现，无可质疑，但是一定要选择好的方法，以免给自己生活带来负面影响。给你推荐位老师，她在这方面擅长你可以先加她微信：<span class=\"wx\"><b><script>document.write(mess2);</script></b></span> 详细向她说明你的情况。<br><br><cite>2016-02-15 21:36</cite></p>");
document.writeln("    <div class=\"ys-tool\"> <a href=\"javascript:;\" target=\"_self\" class=\"up\" title=\"赞一下\">赞（821）</a></div>");
document.writeln("  </div>");
document.writeln("  <div class=\"ys\">");
document.writeln("    <div class=\"ys-msg\"> <img src=\"../../www.doujingqing.com/fengweixin/tx/3.jpg\"/*tpa=http://www.doujingqing.com/fengweixin/tx/3.jpg*/ alt=\"\"> <span>郑静&nbsp;&nbsp;<cite class=\"ellipsis-this\">胸部老师&nbsp;&nbsp;&nbsp;&nbsp;全科</cite></span></div>");
document.writeln("    <p class=\"tiezi-ps\">市面上目前使胸部变大的方法较多，但是只有采取合适正确的使胸部变大方法，才能在自身健康不受到影响的情况下，有效的使胸部变大，建议首先要保证饮食均衡，确保营养的吸收尤其是蛋白质；其次可以使用一些草本使胸部变大方法，改善自己的内分泌情况；最后是选择了对的方法后要坚持下去，不能半途而废，或者中间断断续续。<br><br><cite>2016-04-20 17:34</cite></p>");
document.writeln("    <div class=\"ys-tool\"> <a href=\"javascript:;\" target=\"_self\" class=\"up\" title=\"赞一下\">赞（618）</a></div>");
document.writeln("  </div>");
document.writeln("  <div class=\"ys\">");
document.writeln("    <div class=\"ys-msg\"> <img src=\"../../www.doujingqing.com/fengweixin/tx/2.jpg\"/*tpa=http://www.doujingqing.com/fengweixin/tx/2.jpg*/ alt=\"\"> <span>王泉清&nbsp;&nbsp;<cite class=\"ellipsis-this\">胸部老师&nbsp;&nbsp;&nbsp;&nbsp;全科</cite></span></div>");
document.writeln("    <p class=\"tiezi-ps\">产后胸部缩水是指女人生完孩子胸部不大反小的表现，其原因有：由于哺乳，怀孕都可以导致气血不足，脂肪减少，就会使乳房变小等。确诊后应尽早调理，但不可乱用使胸部变大方法，否则会造成胸部神经损坏，健康有效是两个检验标准。草本使胸部变大方法，不仅能调节身体内分泌情况，还能补充营养，可以做到真正的健康有效。此外，在日常生活中一定要保持良好的心态，避免精神方面过度紧张和生气。<br><br><cite>2016-04-20 21:39</cite></p>");
document.writeln("    <div class=\"ys-tool\"> <a href=\"javascript:;\" target=\"_self\" class=\"up\" title=\"赞一下\">赞（368）</a></div>");
document.writeln("  </div>");
document.writeln("</section>");
document.writeln("<div class=\"content_ri\"> ");
document.writeln("  <!--01-->");
document.writeln("  <dl class=\"content_ri_01\">");
document.writeln("    <dt>相关标签</dt>");
document.writeln("    <div class=\"dotted_line\"></div>");
document.writeln("    <dd><a href=\"#\" style=\"background-color:#e0f3ce\">变大</a> <a href=\"#\">美乳</a> <a href=\"#\">美容</a> <a href=\"#\">整形</a> <a href=\"#\" style=\"background-color:#e0f3ce\">美体</a> <a style=\"background-color:#e0f3ce\" href=\"#\">健身</a> <a href=\"#\">贫乳</a> <a href=\"#\">先天性胸小</a> <a href=\"#\">产后胸部缩水</a></dd>");
document.writeln("  </dl>");
document.writeln("  ");
document.writeln("  <!--02-->");
document.writeln("  <dl class=\"content_ri_02\">");
document.writeln("    <dt>精彩评论</dt>");
document.writeln("    <div class=\"dotted_line\"></div>");
document.writeln("    <div class=\"content_le_03_doctor_box\">");
document.writeln("      <div class=\"content_le_03_doctor\"> <img class=\"doctor_img\" src=\"jipifu_files/img12.jpg"/*tpa=http://qjp.hxhfw.com/jipifu_files/jipifu_files/img12.jpg*/>");
document.writeln("        <ul>");
document.writeln("          <li><span style=\"color:#02879f\">那一夜的风</span> &nbsp;&nbsp;<span>铜牌会员</span> </li>");
document.writeln("          <li>关注板块：健康、妇科、</li>");
document.writeln("          <li> 帮助网友：193&nbsp;&nbsp; 称赞：69</li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("      <div class=\"content_le_03_advice\">");
document.writeln("        <p>胸小的妹子确实伤不起，我是从青春期开始胸部一直都没怎么发育，后来朋友推荐通过草本使胸部变大成功变大的，楼主也可以试试，微信号:<span class=\"wx\"><script>document.write(mess2);</script></span> </p>");
document.writeln("        <br><a class=\"time\"><img src=\"imagesf/ico09.png\"/*tpa=http://qjp.hxhfw.com/jipifu_files/imagesf/ico09.png*/> &nbsp;2016-03-16 09:49:01</a>");
document.writeln("        <p></p>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("    <div class=\"content_le_03_doctor_line\"></div>");
document.writeln("    <div class=\"content_le_03_doctor_box\">");
document.writeln("      <div class=\"content_le_03_doctor\"> <img class=\"doctor_img\" src=\"imagesf/img12.jpg\"/*tpa=http://qjp.hxhfw.com/jipifu_files/imagesf/img12.jpg*/>");
document.writeln("        <ul>");
document.writeln("          <li><span style=\"color:#02879f\">广东省深圳市网友 </span> &nbsp;&nbsp;<span>普通会员</span> </li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("      <div class=\"content_le_03_advice\">");
document.writeln("        <p>胸部偏小一定要尽早调理，否则乳房神经一旦不起作用，就不可能再有使胸部变大的机会。。先收藏，等吃过饭就去咨询。。微信号是:<span class=\"wx\"><script>document.write(mess2);</script></span>吧，已经加上了就等通过呢<br></p>");
document.writeln("          <br><a class=\"time\"><img src=\"imagesf/ico09.png\"/*tpa=http://qjp.hxhfw.com/jipifu_files/imagesf/ico09.png*/> &nbsp;2016-03-18 12:17:23</a>");
document.writeln("        <p></p>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("    <div class=\"content_le_03_doctor_line\"></div>");
document.writeln("    <div class=\"content_le_03_doctor_box\">");
document.writeln("      <div class=\"content_le_03_doctor\"> <img class=\"doctor_img\" src=\"imagesf/img12.jpg\"/*tpa=http://qjp.hxhfw.com/jipifu_files/imagesf/img12.jpg*/>");
document.writeln("        <ul>");
document.writeln("          <li><span style=\"color:#02879f\">湖北省武汉市网友 </span> &nbsp;&nbsp;<span>普通会员</span> </li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("      <div class=\"content_le_03_advice\">");
document.writeln("        <p>产后胸部缩小真的能改善吗？？？我生完孩子已经有段时间了，看看停停，反反复复，就是不能很好的改善，绝望···<br>");
document.writeln("          <br>");
document.writeln("        </p>");
document.writeln("        <div class=\"content_le_03_doctor_box\"> <span id=\"box_span\">回复:</span>");
document.writeln("          <div class=\"content_le_03_doctor\">");
document.writeln("            <ul>");
document.writeln("              <li><span style=\"color:#02879f\">天边的云</span> &nbsp;&nbsp;<span>银牌会员</span> </li>");
document.writeln("            </ul>");
document.writeln("          </div>");
document.writeln("          <div class=\"content_le_03_advice\">");
document.writeln("            <p>我当时按照老师的指导，一个星期不到就感到了变化，现在成功增大了两个罩杯，也没有反弹，你可以加微信:<span class=\"wx\"><script>document.write(mess2);</script></span></p>");
document.writeln("            <br>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("        <p></p><a class=\"time\"><img src=\"imagesf/ico09.png\"/*tpa=http://qjp.hxhfw.com/jipifu_files/imagesf/ico09.png*/> &nbsp;2016-03-19 20:57:25</a>");
document.writeln("        <p></p>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("    <div class=\"content_le_03_doctor_line\"></div>");
document.writeln("    <div class=\"content_le_03_doctor_box\">");
document.writeln("      <div class=\"content_le_03_doctor\"> <img class=\"doctor_img\" src=\"imagesf/img12.jpg\"/*tpa=http://qjp.hxhfw.com/jipifu_files/imagesf/img12.jpg*/>");
document.writeln("        <ul>");
document.writeln("          <li><span style=\"color:#02879f\">江苏省无锡市网友 </span> &nbsp;&nbsp;<span>普通会员</span> </li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("      <div class=\"content_le_03_advice\">");
document.writeln("        <p>为了使胸部变大没少折腾！更没少花钱使用使胸部变大方法！希望这次有帮助，已经加上正在咨询，希望这次可以使胸部变大成功，摆脱“太平公主”的称号。</p>");
document.writeln("        <br><a class=\"time\"><img src=\"imagesf/ico09.png\"/*tpa=http://qjp.hxhfw.com/jipifu_files/imagesf/ico09.png*/> &nbsp;2016-03-25 09:31:43</a>");
document.writeln("        <p></p>");
document.writeln("      </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("    <div class=\"content_le_03_doctor_line\"></div>");
document.writeln("    <div class=\"content_le_03_doctor_box\">");
document.writeln("      <div class=\"content_le_03_doctor\"> <img class=\"doctor_img\" src=\"imagesf/img12.jpg\"/*tpa=http://qjp.hxhfw.com/jipifu_files/imagesf/img12.jpg*/>");
document.writeln("        <ul>");
document.writeln("          <li><span style=\"color:#02879f\">吉林省大连市网友 </span> &nbsp;&nbsp;<span>普通会员</span> </li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("      <div class=\"content_le_03_advice\">");
document.writeln("        <p>每个人都能调理好吗，有不行的同学吗？<br>");
document.writeln("          <br>");
document.writeln("        </p>");
document.writeln("        <div class=\"content_le_03_doctor_box\"> <span id=\"box_span\">回复:</span>");
document.writeln("          <div class=\"content_le_03_doctor\">");
document.writeln("            <ul>");
document.writeln("              <li><span style=\"color:#02879f\">梦想还在</span> &nbsp;&nbsp;<span>金牌会员</span> </li>");
document.writeln("            </ul>");
document.writeln("          </div>");
document.writeln("          <div class=\"content_le_03_advice\">");
document.writeln("            <p>我当时的反应和你差不多，没想到抱着试试的态度竟然找到了宝！建议你试一下，不去尝试永远不会好的，很多人都说方法不错，微信号：<script>document.write(mess2);</script></p>");
document.writeln("            <br>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("        <p></p><a class=\"time\"><img src=\"imagesf/ico09.png\"/*tpa=http://qjp.hxhfw.com/jipifu_files/imagesf/ico09.png*/> &nbsp;2016-04-01 20:57:25</a>");
document.writeln("        <p></p>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("	");
document.writeln("	 <div class=\"content_le_03_doctor_line\"></div>");
document.writeln("    <div class=\"content_le_03_doctor_box\">");
document.writeln("      <div class=\"content_le_03_doctor\"> <img class=\"doctor_img\" src=\"imagesf/img12.jpg\"/*tpa=http://qjp.hxhfw.com/jipifu_files/imagesf/img12.jpg*/>");
document.writeln("        <ul>");
document.writeln("          <li><span style=\"color:#02879f\">广东省深圳市网友 </span> &nbsp;&nbsp;<span>普通会员</span> </li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("      <div class=\"content_le_03_advice\">");
document.writeln("        <p>我也是在老师帮助下成功使胸部变大的，我天生胸小，以为这辈子就这样了，没想到在老师的帮助下竟然迎来了二次发育！ 真的太不可思议了！　<br></p>");
document.writeln("          <br><a class=\"time\"><img src=\"imagesf/ico09.png\"/*tpa=http://qjp.hxhfw.com/jipifu_files/imagesf/ico09.png*/> &nbsp;2016-04-01 22:10:23</a>");
document.writeln("        <p></p>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("	");
document.writeln("	");
document.writeln("    <div class=\"content_le_03_doctor_line\"></div>");
document.writeln("    <div class=\"content_le_03_doctor_box\">");
document.writeln("      <div class=\"content_le_03_doctor\"> <img class=\"doctor_img\" src=\"imagesf/img12.jpg\"/*tpa=http://qjp.hxhfw.com/jipifu_files/imagesf/img12.jpg*/>");
document.writeln("        <ul>");
document.writeln("          <li><span style=\"color:#02879f\">河南省郑州市网友 </span> &nbsp;&nbsp;<span>普通会员</span> </li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("      <div class=\"content_le_03_advice\">");
document.writeln("        <p>555555胸小，说多了都是泪啊！每次买衣服都会纠结，胸部平平撑不起来！</p>");
document.writeln("        <br><a class=\"time\"><img src=\"imagesf/ico09.png\"/*tpa=http://qjp.hxhfw.com/jipifu_files/imagesf/ico09.png*/> &nbsp;2016-04-02 20:13:08</a>");
document.writeln("        <p></p>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("	");
document.writeln("	 <div class=\"content_le_03_doctor_line\"></div>");
document.writeln("    <div class=\"content_le_03_doctor_box\">");
document.writeln("      <div class=\"content_le_03_doctor\"> <img class=\"doctor_img\" src=\"imagesf/img12.jpg\"/*tpa=http://qjp.hxhfw.com/jipifu_files/imagesf/img12.jpg*/>");
document.writeln("        <ul>");
document.writeln("          <li><span style=\"color:#02879f\">广东省梅州市网友 </span> &nbsp;&nbsp;<span>普通会员</span> </li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("      <div class=\"content_le_03_advice\">");
document.writeln("        <p>老公说我胸小摸着没感觉，本来没啥感觉被他一说很在意，心里也很难过！　<br></p>");
document.writeln("          <br><a class=\"time\"><img src=\"imagesf/ico09.png\"/*tpa=http://qjp.hxhfw.com/jipifu_files/imagesf/ico09.png*/> &nbsp;2016-04-05 11:17:23</a>");
document.writeln("        <p></p>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("	");
document.writeln("    <div class=\"content_le_03_doctor_line\"></div>");
document.writeln("    <div class=\"content_le_03_doctor_box\">");
document.writeln("      <div class=\"content_le_03_doctor\"> <img class=\"doctor_img\" src=\"imagesf/img12.jpg\"/*tpa=http://qjp.hxhfw.com/jipifu_files/imagesf/img12.jpg*/>");
document.writeln("        <ul>");
document.writeln("          <li><span style=\"color:#02879f\">广东省深圳市网友 </span> &nbsp;&nbsp;<span>普通会员</span> </li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("      <div class=\"content_le_03_advice\">");
document.writeln("        <p>问一下大家，是直接加上面微信，然后老师就会给你指导吗？<br>");
document.writeln("          <br>");
document.writeln("        </p>");
document.writeln("        <div class=\"content_le_03_doctor_box\"> <span id=\"box_span\">回复:</span>");
document.writeln("          <div class=\"content_le_03_doctor\">");
document.writeln("            <ul>");
document.writeln("              <li><span style=\"color:#02879f\">风一直吹</span> &nbsp;&nbsp;<span>铜牌会员</span> </li>");
document.writeln("            </ul>");
document.writeln("          </div>");
document.writeln("          <div class=\"content_le_03_advice\">");
document.writeln("            <p>老师会先给你解答，然后再给你分析，最后根据你的变大情况，才能给你指导方法，你加下微信自己咨询下就知道了。。。</p>");
document.writeln("            <br>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("        <p></p><a class=\"time\"><img src=\"imagesf/ico09.png\"/*tpa=http://qjp.hxhfw.com/jipifu_files/imagesf/ico09.png*/> &nbsp;2016-04-08 20:57:25</a>");
document.writeln("        <p></p>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("	");
document.writeln("		 <div class=\"content_le_03_doctor_line\"></div>");
document.writeln("    <div class=\"content_le_03_doctor_box\">");
document.writeln("      <div class=\"content_le_03_doctor\"> <img class=\"doctor_img\" src=\"imagesf/img12.jpg\"/*tpa=http://qjp.hxhfw.com/jipifu_files/imagesf/img12.jpg*/>");
document.writeln("        <ul>");
document.writeln("          <li><span style=\"color:#02879f\">广东省深圳市网友 </span> &nbsp;&nbsp;<span>普通会员</span> </li>");
document.writeln("");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("      <div class=\"content_le_03_advice\">");
document.writeln("        <p>生活中丰满的女人确实机会更多一点，别问我是怎么知道的，我去咨询去了  　<br></p>");
document.writeln("          <br><a class=\"time\"><img src=\"imagesf/ico09.png\"/*tpa=http://qjp.hxhfw.com/jipifu_files/imagesf/ico09.png*/> &nbsp;2016-04-09 12:17:23</a>");
document.writeln("        <p></p>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("	");
document.writeln("	");
document.writeln("    <div class=\"content_le_03_doctor_line\"></div>");
document.writeln("    <div class=\"content_le_03_doctor_box\">");
document.writeln("      <div class=\"content_le_03_doctor\"> <img class=\"doctor_img\" src=\"imagesf/img12.jpg\"/*tpa=http://qjp.hxhfw.com/jipifu_files/imagesf/img12.jpg*/>");
document.writeln("        <ul>");
document.writeln("          <li><span style=\"color:#02879f\">吉林省长春市网友 </span> &nbsp;&nbsp;<span>普通会员</span> </li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("      <div class=\"content_le_03_advice\">");
document.writeln("        <p>感谢诸位的推荐，我这就加：<span class=\"wx\"><script>document.write(mess2);</script></span>试一下 ，这次一定要“胸部变大”！！！</p><br><br>");
document.writeln("        ");
document.writeln("         ");
document.writeln("     ");
document.writeln("        <br><a class=\"time\"><img src=\"imagesf/ico09.png\"/*tpa=http://qjp.hxhfw.com/jipifu_files/imagesf/ico09.png*/> &nbsp;2016-04-09 13:40:13</a>");
document.writeln("        <p></p>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("    <div class=\"content_le_03_doctor_line\"></div>");
document.writeln("    <div class=\"content_le_03_doctor_box\">");
document.writeln("      <div class=\"content_le_03_doctor\"> <img class=\"doctor_img\" src=\"imagesf/img12.jpg\"/*tpa=http://qjp.hxhfw.com/jipifu_files/imagesf/img12.jpg*/>");
document.writeln("        <ul>");
document.writeln("          <li><span style=\"color:#02879f\">陕西西安市网友 </span> &nbsp;&nbsp;<span>普通会员</span> </li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("      <div class=\"content_le_03_advice\">");
document.writeln("        <p>因为胸小天天被朋友开玩笑，头都快抬不起来了，现在还是听从过来人的劝告，赶紧大起来吧！</p>");
document.writeln("        <br><a class=\"time\"><img src=\"imagesf/ico09.png\"/*tpa=http://qjp.hxhfw.com/jipifu_files/imagesf/ico09.png*/> &nbsp;2016-04-16 15:22:13</a>");
document.writeln("        <p></p><br>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </dl>");
document.writeln("  ");
document.writeln("  <!--03-->  ");
document.writeln("  <div class=\"content_ri_03\">");
document.writeln("    <h4 class=\"xgwt\">问题相关</h4>");
document.writeln("    <div class=\"dotted_line\"></div>");
document.writeln("    <div class=\"content_ri_03_text\">");
document.writeln("      <ul class=\"list\">");
document.writeln("        <li>");
document.writeln("          <dl><dt style=\"background-color:#e91272\">1</dt><dd>产后胸部下垂并变小，松弛，很难看的。</dd></dl>");
document.writeln("          <p>不要节食减肥　有些妈咪面对自己发胖的身体，急于进行节食减肥，节食的后果是使乳房的脂肪组织也随之受累。乳房随之缩小是必然。对于产后妈咪，体重需要一年左右的时间才能逐渐恢复。</p>");
document.writeln("        </li>");
document.writeln("        <li>");
document.writeln("          <dl><dt style=\"background-color:#fe8007\">2</dt><dd>胸部,比较小,怎样才能变宽变大呢?</dd></dl>");
document.writeln("          <p>你好 女性乳房大小有个体差异、女性乳房的发育还受年龄及各种不同生理时期等因素的影响，因此，乳房的大小没有统一的标准。身材胖一些的女性，由于脂肪组织较多，乳房也会大一些 而身材单薄的女性，则脂肪组织较少，乳房会比较小。</p>");
document.writeln("        </li>");
document.writeln("        <li>");
document.writeln("          <dl><dt style=\"background-color:#ffbe0f\">3</dt><dd>生完孩子胸部变小怎样可以使胸部变大。</dd></dl>");
document.writeln("          <p>方法提取液由以下重量份的原料制得：薯蓣、银杏叶、维E、胶原蛋白、当归、人参等。<br>除了具有常规的使胸部变大功能外，还能够有效缓解产后胸部缩水；采用温和调理为主，用于此现象的改善，取得了良好的效果。</p>");
document.writeln("        </li>");
document.writeln("        <li>");
document.writeln("          <dl><dt>4</dt><dd>吃什么可以帮助胸部变大？</dd></dl>");
document.writeln("          <p>含卵磷脂的黄豆、花生等，含丰富蛋白质的杏仁、核桃、芝麻，都是良好的使胸部变大食物。配合方法调理效果奇好。</p>");
document.writeln("        </li>");
document.writeln("        <li>");
document.writeln("          <dl><dt>5</dt><dd>我26岁胸部很松弛下垂为什么？</dd></dl>");
document.writeln("          <p> 建议服用以下调理如四物胸部变大汤：材料：当归、川芎、薯蓣、银杏叶、白芍、熟地黄。</p>");
document.writeln("        </li>");
document.writeln("        <li>");
document.writeln("          <dl><dt>6</dt><dd>产后如何改善胸部下垂？</dd></dl>");
document.writeln("          <p> 根据你的情况分析，一般还是要注意及时的保养休息很必要，饮食营养，集天然的传统原料，提取植物有效成份时充分保持了原材料的生物活性。通过供给胸部均衡的营养，改善生理功能，使胸部获得充分的养分，可以有效的改胸部微循环状态，吸收所需养分，达到胸部变大的目的。</p>");
document.writeln("        </li>");
document.writeln("      </ul>");
document.writeln("    </div>");
document.writeln("    <br>");
document.writeln("  </div>  ");
document.writeln("</div>");
document.writeln("<div style=\"clear:both\"></div>");
document.writeln("<footer class=\"footer\">");
document.writeln("  <p class=\"footer-version\"><a href=\"javascript:void(0)\" class=\"on\" title=\"触屏版\">触屏版</a></p>");
document.writeln("</footer>");
document.writeln("");